Testing framework
leaksignal/leaksignal pull request #36
Opened 2023-03-31 21:53 UTC by 0rphon

2023-03-31 23:10 UTC, Protryon requested changes

2023-03-31 23:10 UTC, Protryon commented on scripts/testing/leaktester/src/command.rs
> +            self.matches.send(data).await.unwrap();
Rather than await here and potentially cause a buildup in Envoy which might expire, why not just use another unbounded channel like for coverage? Generally I don't use them, but for receiving test data, seems perfect.

2023-03-31 23:10 UTC, Protryon commented on scripts/testing/leaktester/src/command.rs
> +    connected: Arc<AtomicBool>,
A `connected` state should be derived from whether the UpdatePolicy channel is live. Doesn't seem too important here, but Ping isn't guaranteed.

2023-03-31 23:10 UTC, Protryon commented on scripts/testing/leaktester/src/command.rs
> +        while !self.connected.load(Ordering::SeqCst) {}
You shouldn't do this in an async context. Or at all unless in a realtime thread, use a oneshot channel or Notify.

2023-03-31 23:10 UTC, Protryon commented on scripts/testing/leaktester/src/command.rs
> +        assert!(!self.server_handle.1.is_finished());
I'd also use a "is channel alive" check or a "is channel dead on recv" check instead of checking for the Task state. Channels die when dropped on Task completion.

2023-03-31 23:10 UTC, Protryon commented on scripts/testing/leaktester/src/command.rs
> +            .lock()
Why are we using blocking stuff for this? Is this a blocking context? Why?

2023-03-31 23:10 UTC, Protryon commented on scripts/testing/leaktester/src/main.rs
> +    #[arg(short, default_value_t = SocketAddr::V4(SocketAddrV4::new(Ipv4Addr::new(127, 0, 0, 1), 8000)))]
I think it falls out of the scope of this PR, but I'd like to see `leaksignal` and `command` here integrated into the `leaktester` crate. I.e. spawn a local Envoy docker container with a generated configuration and a freshly built, embedded `leaksignal` filter with/without coverage.

2023-04-03 15:31 UTC, 0rphon commented on .cargo/config
> +inherits = "dev"
its super counter-intuitive to the rest of rust but `debug` isn't actually a profile. attempting to build with it causes the error

```
error: config profile `debug-wasm` is not valid (defined in `/mnt/5406d0e6-37e3-4679-9dc2-24193550d990/Work/LeakSignal/command/leaksignal/.cargo/config`)

Caused by:
  profile.debug-wasm.inherits="debug" should be profile.debug-wasm.inherits="dev"
```

2023-04-03 15:55 UTC, 0rphon commented on scripts/local/config/envoy_local_test.yaml
> +bootstrap_extensions:
when i get rid of `bootstrap_extension` leaksignal no longer attempts to talk with command. I've looked through the other examples in both `leaksignal` and `command` and it seems like all the ones that talk with command have the bootstrap section so I'm not sure how to resolve this

2023-04-03 16:04 UTC, 0rphon commented on scripts/testing/leaktester/src/command.rs
> +            self.matches.send(data).await.unwrap();
you know im not sure why i didnt. i think i originally used the normal `sender` for both because that was the first import option then changed the coverage one and forgot to change the matches one

2023-04-03 16:42 UTC, 0rphon commented on scripts/testing/leaktester/src/command.rs
> +        while !self.connected.load(Ordering::SeqCst) {}
yeah im aware it eats cpu and locks a lot, i was just lazy and it was for testing. but yeah my bad

2023-04-03 16:58 UTC, Protryon commented on .cargo/config
> +inherits = "dev"
Huh, interesting.

2023-04-03 16:58 UTC, Protryon commented on scripts/local/config/envoy_local_test.yaml
> +bootstrap_extensions:
Are you perhaps based off non-latest master? I updated all the examples a few days ago IIRC.

2023-04-03 16:59 UTC, Protryon commented on scripts/testing/leaktester/Cargo.toml
> +version = "0.1.0"
I didn't mean to imply it needed to be removed. :P Just double checking it didn't need to match other crate's versions.

2023-04-03 17:47 UTC, Protryon approved these changes

2023-04-03 17:53 UTC, merged