New ratelimit form
leaksignal/leaksignal pull request #4
Opened 2022-12-22 18:30 UTC by Protryon

2022-12-22 20:30 UTC, 0rphon requested changes

2022-12-22 20:30 UTC, 0rphon commented on leakpolicy/src/lib.rs
> +            }
you could also flatten all these match arms into two arms using the `|` match pattern since the arms all have the same variable type. one branch for `Matcher::match_all` and one for `!Matcher::match_all`

2022-12-28 17:25 UTC, Protryon commented on leakpolicy/src/lib.rs
> +            }
The actual problem here was that they shouldn't all be the same. :P

2022-12-28 17:39 UTC, 0rphon approved these changes
LGTM

2022-12-28 21:55 UTC, merged